telegram:
  token: "7475784679:AAFK9Y183wxB_5YriDvkflYzveNwZRAt9vE"
  chat_id: "7642813067"

assets:
  forex:
    - "EUR/USD"
    - "GBP/USD"
    - "USD/JPY"
  crypto:
    - "BTC/USD"
    - "ETH/USD"

settings:
  refresh_interval: 30  # seconds
  max_signals: 5        # per cycle
  max_memory_usage: 80  # percentage
