telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_CHAT_ID"

assets:
  forex:
    - "EUR/USD"
    - "GBP/USD"
    - "USD/JPY"
  crypto:
    - "BTC/USD"
    - "ETH/USD"

settings:
  refresh_interval: 30  # seconds
  max_signals: 5        # per cycle
  max_memory_usage: 80  # percentage
