name: System Health Check

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - name: Check system status
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          STATUS=$(docker inspect -f '{{.State.Status}}' trading-bot)
          if [ "$STATUS" != "running" ]; then
            exit 1
          fi
    - name: Alert on failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: "⚠️ TRADING BOT IS DOWN! Immediate attention required!"
