name: Weekly Model Retraining

on:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 3 AM UTC
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    container: tensorflow/tensorflow:latest-gpu
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Fetch new data
      env:
        AV_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
      run: python scripts/fetch_data.py
    - name: Train models
      run: python scripts/train_models.py
    - name: Commit updated models
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add models/production/
        git commit -m "Update trading models" || echo "No changes"
        git push
    - name: Notify Telegram
      uses: appleboy/telegram-action@master
      with:
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        message: "✅ Models retrained successfully!"
